// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGGyFXubTAo3LwOaJqOTKru_omPzMj_o',
    appId: '1:582573084414:web:e32b9174a27296909ddfaf',
    messagingSenderId: '582573084414',
    projectId: 'authentication-156e5',
    authDomain: 'authentication-156e5.firebaseapp.com',
    storageBucket: 'authentication-156e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6sidu9mBrIr6kvzcOjVbYkIC3K19-ac',
    appId: '1:582573084414:android:cc5185a637e348789ddfaf',
    messagingSenderId: '582573084414',
    projectId: 'authentication-156e5',
    storageBucket: 'authentication-156e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5_deRM6tSC2J5karvjflwRdx_RCuMLg',
    appId: '1:582573084414:ios:f7b2410969febefa9ddfaf',
    messagingSenderId: '582573084414',
    projectId: 'authentication-156e5',
    storageBucket: 'authentication-156e5.appspot.com',
    iosBundleId: 'com.example.authenticationFlutterFirebaseCrudByKkk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5_deRM6tSC2J5karvjflwRdx_RCuMLg',
    appId: '1:582573084414:ios:1fe35ba0b4e4b4d79ddfaf',
    messagingSenderId: '582573084414',
    projectId: 'authentication-156e5',
    storageBucket: 'authentication-156e5.appspot.com',
    iosBundleId: 'com.example.authenticationFlutterFirebaseCrudByKkk.RunnerTests',
  );
}
